### PR TITLE
Jnci spacewar 11092018

### PR DESCRIPTION
**Pull request by jamesneimanconsulting**
@sidsharma27 Kindly review and merge if approved.

### CODE REVIEW

**Comment by jamesneimanconsulting** [comment]
@sidsharma27 Please merge this in: it contains the chinese link you requested.

**Comment by jamesneimanconsulting** [comment]
@sidsharma27 please merge. I've updated the chinese link.

**Comment by plutoless** [comment]
pls move the long readme code explanation to a separate guide.md file

**Comment by jamesneimanconsulting** [comment]
Closing and replacing with PR https://github.com/AgoraIO/Voice-Call-for-Mobile-Gaming/pull/12

**Pull request closed without merging**
