### PR TITLE
Jnci vcmg 10262018

### PR DESCRIPTION
**Pull request by jamesneimanconsulting**
@sidsharma27 Kindly review and merge if approved.

### CODE REVIEW

**Comment by jamesneimanconsulting** [comment]
@sidsharma27 Please merge this in: it contains the chinese link you requested.

**Comment by jamesneimanconsulting** [comment]
@sidsharma27 please merge: I've updated the chinese link.

**Comment by plutoless** [comment]
pls resolve conflict first

**Comment by plutoless** [comment]
plus please move the long readme into a separate guide.md file @sidsharma27

**Comment by jamesneimanconsulting** [comment]
https://github.com/AgoraIO/Voice-Call-for-Mobile-Gaming/pull/12

**Pull request closed without merging**
